### ISSUE TITLE
CODE RUB: User Refactoring Foundations Completion

### ISSUE THREAD

**Issue by glhays** [SlimAhmad/Jaunts.Core#13]
These mods are an initial step to refactor the user system towards compliance of the Standard. Although initial thoughts are by using the complete AspNetCore.Identity system will introduce a hard coupled dependency. It may never fulfill the All-In or All-Out compliance rule.

The other issue presented recently about Orchestrations not adhering to the 2-3 rule may be in the fact that the User Foundations are either not complete or structured to use the identity system like a "toaster" where the user is dependent on the Identity code to provide the functional support of many of the userServices class.
The associated PR to this issue doesn't break any current implementation present at the time pushing.
PR is meant to be looked over before pushing to the master, or pushing and if needed reverting.

**Comment by SlimAhmad** [comment]
@glhays Thank you, I will work on it, I just noticed there's no unit test for some methods in the userService.
I'm still finding it hard to ensure it adheres to the rule.
